# Generated by Django 5.0.1 on 2024-02-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='emal',
            new_name='email',
        ),
    ]
