# Generated by Django 5.0.1 on 2024-02-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
