# Generated by Django 5.0.1 on 2024-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
